dronetag/flutter-opendroneid

ios/Classes/Scanner/BluetoothScanner.swift

Solves exception thrown when bt is turned on/off on phone and solves wrong bt state shown after app is restarted.

Fix bt state handling on ios

---

android/src/main/kotlin/cz/dronetag/flutter_opendroneid/OdidMessageHandler.kt

Use getOrElse method When converting enum ordinal to value in Android parser.

fix: check if enum ordinal is in enum values range

---

android/src/main/java/cz/dronetag/flutter_opendroneid/Pigeon.java
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/FlutterOpendroneidPlugin.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/BluetoothScanner.kt
ios/Classes/Scanner/BluetoothScanner.swift
ios/Classes/SwiftFlutterOpendroneidPlugin.swift
ios/Classes/pigeon.h
ios/Classes/pigeon.m
lib/flutter_opendroneid.dart
lib/pigeon.dart
pigeon/schema.dart

Add method to set scan priority to platform API. On Android, set ScanMode according to priority. On ios, implement timer that periodically restarts scan to maintain high priority.
Also removes unused autoRestart member variable

Feature: bt scan priority

---

lib/flutter_opendroneid.dart
lib/models/permission_missing_exception.dart
lib/models/permissions_missing_exception.dart
pubspec.yaml

Request permissions before starting scans
iOS requires just bluetooth permissions. 
Android requires bluetooth, bluetoothScan and location for bt scanning. I tested scanning without location permission on Android 9 and 12  and it seems that it is required on both versions, because I did not get any data with location disabled.
Location is also required for [Wi-Fi scanning on Android.](https://developer.android.com/guide/topics/connectivity/wifi-scan)

Feature: check bluetooth permissions

---

ios/Classes/SwiftFlutterOpendroneidPlugin.swift

Should solve issues with scanning in iOS. Completion was never called e.g.  when starting bt scan. The method never completed, so listener initialization which was meant to run after starting scan never happened.  It did not happen in mobile app, because there the order is different.

fix: call complete callback in swift plugin methods

---

android/src/main/AndroidManifest.xml
lib/flutter_opendroneid.dart

Android 13 introduces new _nearbyWifiDevices_ permission ,it replaces need to have location permission for Wi-Fi scans.

feature: check new android 13 Wi-Fi permission

---

lib/flutter_opendroneid.dart

Throw `PermissionMissingException` when starting Bluetooth scans without location permission on Android.
Android requires location permission for bt scanning for Android SDK 33.
We can go around it by asserting ['neverForLocation' flag](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#assert-never-for-location), but some data may be filtered out, so I decided we would require location for Bluetooth scanning.
User must select "while using the app" option when asked about location usage in order for scans to work when app is in background.

fix: require loc permission for bt scan on Android

---

lib/flutter_opendroneid.dart
lib/models/compare_extension.dart

Do not update pack if pack already contains the same data as new message, e.g. same location with same timestamp.
I included all message types, so e.g. when BasicId comes with same uasId, pack is not updated.
This improves performance, but lowers the number of messages processed, so e.g. rssi is not updated as often so this information can be outdated. Maybe we should use this just for location, I will leave it for discussion.

De-duplicate data using fields comparison

---

android/build.gradle

Bump `targetSDKVersion` and `compileSDKVersion` to 33.

chore: bump Android SDK version

---

lib/extensions/compare_extension.dart
lib/flutter_opendroneid.dart
lib/models/message_container.dart
lib/utils/conversions.dart
pubspec.yaml

Added re-export for `dart-opendroneid` types to `flutter-opendroneid`, so that the types can be used from apps without the need to depend on `dart-opendroneid` directly.
Please wait for https://github.com/dronetag/dart-opendroneid/pull/2 to be merged and bump `dart-opendroneid` version in this PR.
DT-2637

Re-exported Dart ODID types

---

lib/utils/conversions.dart

Fix implementation was using `runtimeType` in switch.

fix: uasid asString conversion

---

.github/workflows/integration.yml
.github/workflows/publish.yml
README.md
android/build.gradle
android/gradle.properties
android/gradle/wrapper/gradle-wrapper.properties
pubspec.yaml

Upgraded Gradle to 7.6.3, unified configuration so it is consistent with our other packages and fixed a few issues due to outdated Gradle config.
Bumped `pubspec.yaml` dependencies.
Bumped Flutter CI to 3.16.7

Upgraded outdated packages and fixed Gradle issues

---

.github/workflows/integration.yml
.github/workflows/publish.yml

Standard Dronetag Flutter pipeline now enforces `pubspec.lock` unless explicitly disabled. Since `pubspec.lock` is not shared for libraries, this PR disables the enforcement.

Pubspec lock now not enforced

---

android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/WifiNaNScanner.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/WifiScanner.kt

Wifi adapter state receiver which is registered when wifi scanner is started was not unregistered upon `cancel()` call. When app was sent to background and receiver tried to handle incoming message an exception was raised because of missing background location permissions.
Receiver is now unregistered when scanning is cancelled.

Added missing wifi state receiver unregistration on cancel

---

.github/workflows/publish.yml
.github/workflows/release.yml
.releaserc

Separated release and publish CI pipeline into two steps:
- release - runs on every commit to `master`, except for `chore(release)` commits done by `semantic-release`
- publish - runs on every version tag push
Release is now entirely handled by `semantic-release`. New version is calculated, changelog is generated, `pubspec.yaml` updated, new version tag is pushed and finally a Github release is created.
To trigger the publish pipeline from another Github Action (in this case the release action), the version tag push must be done using PAT (personal access token) of a user, not using the pipeline token. The release pipeline expects `secrets.RELEASE_PAT` to be present.

Separated release and publish CI step

---

android/src/main/java/cz/dronetag/flutter_opendroneid/Pigeon.java
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/BluetoothScanner.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/ODIDScanner.kt
ios/Classes/Scanner/BluetoothScanner.swift
ios/Classes/pigeon.h
ios/Classes/pigeon.m
lib/exceptions/odid_message_parsing_exception.dart
lib/flutter_opendroneid.dart
lib/pigeon.dart
pigeon/schema.dart

Throw `ODIDMessageParsingException` when parsing of odid message fails. The exception contains metadata such as mac address, bluetooth name, rssi, timestamp, source.
Add missing bluetooth name to `ODIDPayload`.
Example in Sentry: [APP-2HZ](https://sentry.dronetag.cz/organizations/dronetag/issues/4699/).
After this will be merged I will use it in app: https://github.com/dronetag/app/pull/411.

Include Bluetooth metadata to parsing exceptions

---

android/src/main/kotlin/cz/dronetag/flutter_opendroneid/FlutterOpendroneidPlugin.kt
ios/Classes/SwiftFlutterOpendroneidPlugin.swift
lib/flutter_opendroneid.dart
lib/models/dri_source_type.dart

Refactor FlutterOpendroneId API for the DroneScanner 2.0.
I created 2 event channels, one for bt and one for wifi. Now there are 2 streams, 1 for each technology. 
I also refactored start/stop methods, so it is possible to control wifi/bt separately.

refactor: split message event channels for wifi and bt

---

android/src/main/kotlin/cz/dronetag/flutter_opendroneid/FlutterOpendroneidPlugin.kt

I noticed crashes from flutter-opendroneid in DroneScanner google play console.
Main reason for crashes was stoping scans from `onDetachedFromEngine`, even though there were never started or were unsupported (Wi-Fi NaN scans).
Also, i suspect that sentry is configured wrong for DroneScanner because none of this issues appeared in Sentry,

Fix: resolve android crashes

---

lib/models/received_odid_message.dart

Added `copyWith` implementation for `ReceivedODIDMessage` to allow easier manipulation with the container elsewhere. If it was omitted intentionally I can also implement it in the library using flutter-opendroneid.
DT-3744

Implemented `copyWith` for `ReceivedODIDMessage`

---

android/src/main/java/cz/dronetag/flutter_opendroneid/Pigeon.java
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/BluetoothScanner.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/ODIDScanner.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/WifiNaNScanner.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/WifiScanner.kt
ios/Classes/Scanner/BluetoothScanner.swift
ios/Classes/pigeon.h
ios/Classes/pigeon.m
lib/flutter_opendroneid.dart
lib/models/message_container.dart
lib/pigeon.dart
pigeon/schema.dart

Add ODIDMetadata class to pigeon schema. ODIDMetadata contains metadata that were previously saved in MessageContainer plus new transmission information used in data collection: bluetooth phy, frequencies etc.

Feat: add extended ODIDMetadata

---

README.md
android/src/main/java/cz/dronetag/flutter_opendroneid/Pigeon.java
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/Exceptions.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/FlutterOpendroneidPlugin.kt
ios/Classes/PluginNotInitializedException.swift
ios/Classes/SwiftFlutterOpendroneidPlugin.swift
ios/Classes/pigeon.h
ios/Classes/pigeon.m
lib/flutter_opendroneid.dart
lib/pigeon.dart
pigeon/schema.dart

Add `initialize()` and `bool isInitialized` to platform API. implement initialization on both iOS and Android. This prevents permission requests immediately on app start on iOS.
in `SwiftFlutterOpendroneidPlugin`, bluetooth scanner is now nullable. Instantiate scanner in initialize method. Plugin is initialized when scanner is not null. Calling methods that use bluetooth scanner before initialization throws `PluginNotInitializedException` with ` "Plugin was not initialized"` message.
Similar change as on iOS, create all scanners in initialize method. `Activity` and `Context` which are provided in `onAttachedToActivity` are required when creating scanners, so I saved them to `FlutterOpendroneidPlugin`. `PluginNotInitializedException` is thrown when using API before init. …

feat: add initialize method

---

android/src/main/java/cz/dronetag/flutter_opendroneid/Pigeon.java
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/FlutterOpendroneidPlugin.kt
android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/BluetoothScanner.kt
ios/Classes/Scanner/BluetoothScanner.swift
ios/Classes/SwiftFlutterOpendroneidPlugin.swift
ios/Classes/pigeon.h
ios/Classes/pigeon.m
ios/Classes/utils/Utils.swift
lib/flutter_opendroneid.dart
lib/pigeon.dart
pigeon/schema.dart

Based on `beta` branch.
The `startScan` function now optionally allows specifying different BT service UUID from which ODID packets are expected. Default value is `FFFA` which is standardized as "ASTM RID".
Internally, service UUID is no longer a constant, but a value computed from currently set "short service UUID" (e.g. `FFFA`) value. Bluetooth scanner now implements `setServiceUuid` which configures this short service UUID and restarts scanning if necessary.
Tested in Dronetag App (further changes necessary, see Jira issue for more details).

Added support for different Bluetooth RID service UUID

---

android/src/main/kotlin/cz/dronetag/flutter_opendroneid/scanner/BluetoothScanner.kt

**Context:**
On Android, app can scan using BT even when BT is disabled in system settings. To keep the behaviour consistent we cancel scan when BT is system disabled, DS2 shows that BT is unavailable.
But there was an error that caused scan to not cancel, app continued to receive data even when BT is disabled on system.
**Fix:**
I fixed the `cancel` method in `BluetoothScanner.kt`.
There was check ` if (!bluetoothAdapter.isEnabled) return` that was supposed to prevent canceling when scanning is not active, but it was wrong. `bluetoothAdapter.isEnabled `is just other way of writing `adapterState == .stateOn`, so cancel returned early and did not actually cancel the scan when BT was disabled (`adapterState == .stateOff`).  
I replaced it with `if (!isScanning) return`.
**Testing:**
Build …

fix(android): cancel scan when bluetooth is system disabled
